"""Is `_enumerate_round_shapes` throwing away the cheapest shape for a delivery?

`offer()` de-duplicates shapes by `delta = ks * parallel` (the pieces each order
receives, which is what the closing sweep actually spends).  When two shapes give
the same `delta`, the cheaper one is the one with the LARGER `parallel`, because
`knives = sum(ks) + 1` and `sum(ks) = sum(delta) / parallel`.  The code keeps the
SMALLER parallel (it walks `parallel` ascending and rejects any later, wider,
re-offer), i.e. it keeps the shape that pays more knives for the same delivery.

This probe measures how often that fires and how many knives it costs, by
enumerating the same geometry independently and comparing, per delta, the kept
shape against the widest legal one.
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
import solver as S  # noqa: E402

DATA = ROOT / 'data' / 'semi'


def build():
    settings = json.loads((DATA / 'competition.config.json').read_text(encoding='utf-8'))
    settings.update(continuity=True, coverage_shared=True, enforce_order_mass_floor=True,
                    objective='platform_score', baseline_knives=160000)
    cfg = S.Config(**settings)
    orders = S.load_orders(str(DATA / 'orders.normalized.csv'), cfg, skip_invalid=True)
    blanks = S.load_blanks(str(DATA / 'blanks.normalized.csv'))
    return cfg, orders, S.Model(orders, cfg, blanks)


def brute_max_p(model, ids, cfg, blank_len):
    """delta -> (best parallel, ks, knives) over EVERY legal shape, no budget.

    A blind product over `max_seg` explodes (32^5 for a five-order group), so the
    cut vectors are generated by a length-budgeted DFS instead: a partial sum can
    only grow, so any prefix already past `bed_length` prunes its whole subtree.
    """
    sizes = [model.orders[i].size for i in ids]
    linear = model.orders[ids[0]].linear_weight
    plimit = model.parallel_limit(ids)
    budget = cfg.bed_length - cfg.round_trim
    cuts = []

    def walk(j, used, acc):
        if j == len(sizes):
            if used >= cfg.min_bed_length - 1e-8:
                cuts.append(tuple(acc))
            return
        kmax = int((budget - used) // sizes[j])
        for k in range(kmax, -1, -1):
            acc.append(k)
            walk(j + 1, used + k * sizes[j], acc)
            acc.pop()

    walk(0, 0.0, [])
    table = {}
    for parallel in range(1, plimit + 1):
        for ks in cuts:
            if not any(ks):
                continue
            lengths = [k * s for k, s in zip(ks, sizes) if k]
            total = sum(lengths) + cfg.round_trim
            if total * parallel * linear > cfg.bed_weight + 1e-8:
                continue
            if max(lengths) + cfg.round_trim > blank_len + 1e-8:
                continue
            delta = tuple(k * parallel for k in ks)
            knives = sum(ks) + 1
            old = table.get(delta)
            if old is None or knives < old[2]:
                table[delta] = (parallel, ks, knives)
    return table


def _product(ranges):
    out = [()]
    for r in ranges:
        out = [t + (v,) for t in out for v in r]
    return out


def probe(cfg, model, ids, label):
    ids = tuple(sorted(ids))
    blank = model.catalogue(ids)[0]
    sizes = [model.orders[i].size for i in ids]
    linear = model.orders[ids[0]].linear_weight
    blank_len = model.blank_length(ids, blank)
    plimit = model.parallel_limit(ids)
    got = S._enumerate_round_shapes(model, ids, sizes, linear, blank_len, plimit, cfg)
    kept = {m[0]: (m[1], m[2], sum(m[2]) + 1) for m in got}
    best = brute_max_p(model, ids, cfg, blank_len)
    wider = [d for d in kept if d in best and best[d][0] > kept[d][0]]
    lost = sum(kept[d][2] - best[d][2] for d in wider)
    print(f'--- {label}  ids={len(ids)} dia={model.orders[ids[0]].diameter} '
          f'sizes={sorted(set(round(s, 2) for s in sizes))} plimit={plimit}')
    print(f'    shapes kept by solver      {len(kept):>7,}   (brute legal deltas {len(best):,})')
    print(f'    deltas with a wider shape  {len(wider):>7,}   ({len(wider) / max(1, len(kept)):.1%} of kept)')
    print(f'    knives thrown away         {lost:>7,}   over those deltas')
    if wider:
        d = max(wider, key=lambda x: kept[x][2] - best[x][2])
        print(f'    worst case: delta={d} kept p={kept[d][0]} k={kept[d][1]} '
              f'kn={kept[d][2]}  ->  widest p={best[d][0]} k={best[d][1]} kn={best[d][2]}')
    return len(kept), len(wider), lost


def main():
    cfg, orders, model = build()
    index = {o.oid: i for i, o in enumerate(orders)}
    plan = json.loads((ROOT / 'submission_semi_nolimit' / '复赛结果_棒材优化.json')
                      .read_text(encoding='utf-8'))
    picked = {}
    for batch in plan:
        for oid in batch['orders']:
            dia = orders[index[oid]].diameter
            cur = picked.get(dia)
            if cur is None or len(batch['orders']) < len(cur):
                picked[dia] = batch['orders']
    print(f'sampled groups (smallest batch per diameter): '
          f'{ {d: len(v) for d, v in sorted(picked.items())} }\n', flush=True)
    tot_kept = tot_wider = tot_lost = 0
    for dia in (43.0, 26.5, 36.0, 20.0):
        if dia not in picked:
            continue
        ids = [index[o] for o in picked[dia] if o in index]
        k, w, l = probe(cfg, model, ids, f'dia {dia}')
        tot_kept += k
        tot_wider += w
        tot_lost += l
    print(f'\nTOTAL  kept {tot_kept:,} shapes, {tot_wider:,} have a wider twin, '
          f'{tot_lost:,} knives recoverable on this sample')


if __name__ == '__main__':
    main()
