#!/usr/bin/env bash
# Build the machine-migration bundles.
#
# Two archives, because they have different audiences:
#
#   1. `jinyinsai1_nolimit-src.zip`  -- the git-tracked tree at HEAD, no history,
#      no `runs/`.  This is what you check out on the new machine.
#   2. `migration-bundle.zip`        -- the same tree PLUS the conversation
#      transcript, the git bundle (full history), and the delivered packages.
#      This is the one to carry on a USB stick / cloud drive.
#
# `runs/` (864 MB) is deliberately excluded: every file in it is regenerated by
# the commands in MIGRATION.md and README.md.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/migration_out}"
mkdir -p "$OUT"

echo "==> repository: $ROOT"
git -C "$ROOT" rev-parse --short HEAD

echo
echo "==> 1/3 git bundle (full history, all branches)"
git -C "$ROOT" bundle create "$OUT/jinyinsai1_nolimit.git-bundle" --all

echo
echo "==> 2/3 source tree at HEAD (no history, no runs/)"
git -C "$ROOT" archive --format=zip -o "$OUT/jinyinsai1_nolimit-src.zip" HEAD

echo
echo "==> 3/3 migration bundle (source + transcript + history + packages)"
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

git -C "$ROOT" archive --format=tar HEAD | (cd "$STAGE" && tar xf -)
mkdir -p "$STAGE/conversation"
cp "$ROOT"/conversation/*.jsonl "$ROOT"/conversation/*.md "$STAGE/conversation/" 2>/dev/null || true
cp "$OUT/jinyinsai1_nolimit.git-bundle" "$STAGE/"

cat > "$STAGE/读我先.md" <<'NOTE'
# 迁移包内容

## 最快的恢复路径

```bash
git clone jinyinsai1_nolimit.git-bundle jinyinsai1_nolimit
cd jinyinsai1_nolimit
git checkout semi-final
```

然后读 `MIGRATION.md`。

## 目录

| 路径 | 说明 |
|---|---|
| `MIGRATION.md` | **先读这个**：恢复步骤、各包成绩、09-23 事故、已知坑 |
| `COMPARISON_in_package_two_tracks.md` | 与包内另一条 AI 交付线的对比（含取整口径风险量化） |
| `conversation/*.jsonl` | 本对话的原始归档，放回 WorkBuddy 的 projects 目录即可恢复 |
| `conversation/对话记录_可读版.md` | 同一对话的可读版（工具调用已摘要） |
| `jinyinsai1_nolimit.git-bundle` | 完整 git 历史（所有分支），可 clone |
| `submission_semi_*/` | 五个复赛交付包，全部已修 0 违规 |
| `diagnostics/` | 诊断与证据脚本，报告引用的每个数字都由它们产出 |
| `data/semi/` | 复赛数据（归一化 + 原始） |

## 不包含

- `runs/`（864 MB）：全部可复现，按 `MIGRATION.md` §5 重跑
- `*.exe`：编译器相关，用 `build_kernels.py` 重编
NOTE

(cd "$STAGE" && zip -qr "$OUT/migration-bundle.zip" .)

echo
echo "==> done"
ls -la "$OUT"
