#!/usr/bin/env bash
# Build the complete machine-migration bundle covering ALL THREE repositories.
#
# Audience and layout:
#
#   jinyinsai1_migration/
#     READ_ME_FIRST.md                     <- start here on the new machine
#     repos/
#       jinyinsai1_nolimit.git-bundle      full history, all branches (the main line)
#       jinyinsai1.git-bundle              full history, both branches (shared + other line)
#       auto_review.git-bundle             full history (AIC leaderboard control plane)
#     jinyinsai1_nolimit-src.zip           untracked/source snapshot, no history
#     conversation/                        this chat, raw + readable
#     MIGRATION.md                         deep notes, scores, gotchas
#     evidence/                            cross-checks referenced by the reports
#
# `runs/` (864 MB in jinyinsai1, none in nolimit) is deliberately NOT shipped:
# every artefact in it is regenerated by the commands in MIGRATION.md.
#
# Usage:  bash tools/make_full_migration.sh [OUTDIR]
set -euo pipefail

NOLIMIT="D:/02_Projects/ML/jinyinsai1_nolimit"
MAIN="D:/02_Projects/ML/jinyinsai1"
AUTO="$MAIN/auto_review"
OUT="${1:-$NOLIMIT/migration_out}"
STAGE="$OUT/stage"

mkdir -p "$STAGE/repos" "$STAGE/conversation"

echo "==> 1/6 git bundles (full history)"
git -C "$NOLIMIT" bundle create "$STAGE/repos/jinyinsai1_nolimit.git-bundle" --all
git -C "$MAIN"    bundle create "$STAGE/repos/jinyinsai1.git-bundle"        --all
git -C "$AUTO"    bundle create "$STAGE/repos/auto_review.git-bundle"      --all

echo "==> 2/6 nolimit source tree at HEAD (no history, no runs/)"
git -C "$NOLIMIT" archive --format=zip -o "$OUT/jinyinsai1_nolimit-src.zip" HEAD

echo "==> 3/6 nolimit tracked tree into the stage"
git -C "$NOLIMIT" archive --format=tar HEAD | (cd "$STAGE" && tar xf -)

echo "==> 4/6 conversation transcript"
cp "$NOLIMIT"/conversation/*.jsonl "$STAGE/conversation/" 2>/dev/null || true
cp "$NOLIMIT"/conversation/*.md    "$STAGE/conversation/" 2>/dev/null || true

echo "==> 5/6 evidence for the clause-6 cross-check"
mkdir -p "$STAGE/evidence"
cp "$NOLIMIT"/evidence/rival_semi_371f209.json "$STAGE/evidence/" 2>/dev/null || true

echo "==> 6/6 entry note"
cat > "$STAGE/READ_ME_FIRST.md" <<'NOTE'
# 迁移包 — 先读这个

三个仓库、一份对话、一份证据。本文件只讲**怎么恢复**；成绩、事故、坑
都在 `MIGRATION.md`。

## 一、恢复代码（三个仓库）

每个 `.git-bundle` 都能直接 clone，历史与分支完整：

```bash
mkdir -p ~/proj && cd ~/proj

# 主开发线（复赛求解器 + 五个交付包 + 诊断）
git clone repos/jinyinsai1_nolimit.git-bundle jinyinsai1_nolimit
cd jinyinsai1_nolimit && git checkout semi-final && cd ..

# 共享仓：含另一条交付线的 main 分支
#
# 注意：clone 只物化远端 HEAD（main）。`semi-final` 在 bundle 里以
# `refs/remotes/origin/semi-final` 存在但不会被检出，且 clone 后该
# remote-tracking ref 也不可用 —— 按 SHA 直接建分支（SHA 见下）：
git clone repos/jinyinsai1.git-bundle jinyinsai1
cd jinyinsai1
git checkout -b semi-final 857ab8c7ea1221799a66516c4166688103a92078
cd ..

# 自动打榜（AIC Leaderboard Control，零第三方依赖的 stdio MCP 服务）
git clone repos/auto_review.git-bundle auto_review
```

clone 之后把远端指回 GitHub（bundle 是离线的，origin 会指到本地路径）：

```bash
cd jinyinsai1_nolimit && git remote set-url upstream git@github.com:WRw5w/jinyinsai1.git
cd ../jinyinsai1       && git remote set-url origin   https://github.com/WRw5w/jinyinsai1.git
cd ../auto_review      && git remote set-url origin   https://github.com/WRw5w/auto-.git
```

只想拿最新源码、不要历史：解压 `jinyinsai1_nolimit-src.zip` 即可。

## 二、恢复这次对话

`conversation/` 下两份：

| 文件 | 用途 |
|---|---|
| `*.jsonl` | **原始归档**。放回 WorkBuddy 的 projects 目录即可恢复会话 |
| `对话记录_可读版.md` | 人读的（工具调用已摘要，163 轮 / 690 KB） |

## 三、不包含什么

- **`runs/`**（两个仓合计约 864 MB）：全部可由 `MIGRATION.md` §5 的命令重跑。
  你上次已明确"不带，全部重新跑"。
- **`*.exe`**：编译器产物，用 `build_kernels.py` 重编。

## 四、恢复后立刻验证

```bash
cd jinyinsai1_nolimit
python -X utf8 -m unittest test_semi_solver test_solver test_semi_check test_platform_score
# 期望：43 tests OK

python -X utf8 diagnostics/verify_clause6_readings.py
# 期望两行 OK：
#   OK: reading B reproduces the official 7030; reading C does not.
#   OK: every package's .zip and .json agree (no stale copy can ship).
```

这两条是这次迁移**最重要的自检**：

1. 第一条确认你的环境仍能复现官方的 7030 违规锚点，即确认你没有把 clause 6
   的判据改错成另一个方向（改错会让你把 0 分包当成满分包交上去）。
2. 第二条确认每个交付目录里 `.zip` 与 `.json` 一致 —— **上传用的是 `.zip`，
   漂移的 `.json` 是个 0 分陷阱**（已经有 3 个目录踩过）。

细节见 `MIGRATION.md` §3.5.1 与 §3.5.2。
NOTE

echo "==> packaging"
rm -f "$OUT/migration-bundle-ALL.zip"
( cd "$STAGE" && zip -qr "$OUT/migration-bundle-ALL.zip" . )
# Deliberately NOT deleting $STAGE: the sandbox blocks bulk recursive deletes
# (>50 files) inside the workspace.  The staging tree is useful anyway -- it is
# the same content in expanded form.  Remove it by hand if you want it gone.

echo
echo "==> done"
ls -la "$OUT"
