"""Regenerate validation_report.json so it matches the ZIP bytes that will ship.

Why this exists: `build_submission.py` writes the report in the same run that
writes the ZIP, so the two agree.  But when a package ships through several
repair passes -- as happened on 2026-09-23, when `fix_continuity_order.py` and
`rotate_scheme_rounds` rebuilt three ZIPs in place -- the report is left behind
describing the ZIP that no longer exists.

The failure is quiet and dangerous: `submission_semi_merged_v2/validation_report
.json` claimed `sha256 = 852c9b84...` while the directory's ZIP was `49862fc7...`.
A report whose hash does not match the artifact is worthless as delivery
evidence, and worse, it invites a reviewer to conclude the package is fine when
nobody has actually validated the bytes on disk.

This script:
  1. reads the ZIP's real bytes and hashes them,
  2. re-opens the ZIP, extracts the solution JSON, and re-runs the independent
     platform-contract check on those exact bytes,
  3. re-runs the estimator,
  4. rewrites the report with the matching hash.

It never writes to the ZIP.  Run it after any repair that touches a package.

Usage:
    python -X utf8 tools/resync_reports.py submission_semi_merged_v2 [...]
    python -X utf8 tools/resync_reports.py --all
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from platform_check import check as platform_check            # noqa: E402
from platform_score import evaluate as platform_evaluate      # noqa: E402
from platform_score import load_scoring_data                  # noqa: E402


def solution_json_name(names: list[str]) -> str:
    cands = [n for n in names if n.endswith('.json')]
    if len(cands) != 1:
        raise ValueError(f'expected exactly one json in the archive, got {cands}')
    return cands[0]


def resync(pkg: Path, data: Path) -> dict:
    zips = list(pkg.glob('*.zip'))
    if len(zips) != 1:
        raise ValueError(f'{pkg}: expected exactly one zip, found {[z.name for z in zips]}')
    zip_path = zips[0]

    raw = zip_path.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()

    with zipfile.ZipFile(zip_path) as archive:
        name = solution_json_name([n for n in archive.namelist() if not n.endswith('/')])
        packed = archive.read(name)
        if archive.testzip() is not None:
            raise ValueError(f'{zip_path}: CRC failure')
    plan = json.loads(packed.decode('utf-8'))

    contract = platform_check(plan, data=data, round='semi')
    estimator = platform_evaluate(plan, data=data, round_name='semi')
    violations = estimator.get('violations') or {}

    report = {
        'package': pkg.name,
        'zip': zip_path.name,
        'zip_bytes': len(raw),
        'sha256': digest,
        'inner_json': name,
        'inner_sha256': hashlib.sha256(packed).hexdigest(),
        'schemes': len(plan),
        'rounds': sum(len(b.get('length_scheme') or []) for b in plan),
        'platform_check_passed': bool(contract.get('passed')),
        'platform_check_errors': contract.get('error_counts') or {},
        'violations': violations,
        'violation_count': sum(violations.values()),
        'notes': ('Regenerated by tools/resync_reports.py so the recorded hash '
                  'matches the ZIP on disk.  Absence of continuity_seam in '
                  'violations means the package is clean under reading B; see '
                  'diagnostics/clause6_predicate_resolved_20260923.md for why '
                  'reading B is the platform rule and set-equality is not.'),
    }

    out = pkg / 'validation_report.json'
    if (pkg / 'validation_report_source.json').exists():
        out = pkg / 'validation_report_source.json'   # do not clobber the source copy
    out.write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    return report


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('packages', nargs='*', help='package directories')
    ap.add_argument('--all', action='store_true',
                    help='every submission_semi_* directory under the repo root')
    ap.add_argument('--data', default='data/semi')
    args = ap.parse_args()

    pkgs = [ROOT / p for p in args.packages]
    if args.all:
        pkgs = sorted(p for p in ROOT.glob('submission_semi_*') if p.is_dir())
    if not pkgs:
        ap.error('name at least one package, or pass --all')

    data = ROOT / args.data
    bad = 0
    for pkg in pkgs:
        try:
            rep = resync(pkg, data)
        except Exception as exc:                              # noqa: BLE001
            print(f'{pkg.name:32} ERROR: {exc}')
            bad += 1
            continue
        ok = rep['platform_check_passed'] and rep['violation_count'] == 0
        print(f'{pkg.name:32} {rep["sha256"][:16]}  '
              f'passed={rep["platform_check_passed"]}  '
              f'violations={rep["violation_count"]}  {"OK" if ok else "CHECK"}')
        if not ok:
            bad += 1
    print()
    if bad:
        print(f'{bad} package(s) need attention.')
        return 1
    print('All reports now match their ZIP bytes.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
